name: Deploy to VPS with Docker Compose

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and Deploy with Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx (локально, если нужно)
        uses: docker/setup-buildx-action@v3

      - name: Copy project files to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/deploy/next-app"

      - name: Deploy with docker-compose on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/deploy/next-app
            docker-compose down
            docker-compose up -d --build
